version: "3"
services:
  api:
    build: .
    env_file: .env
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run start:dev

    networks:
      - backend


networks:
  backend:
    driver: bridge